### ISSUE TITLE
As per your SO response, I tried using grunt-ts in my project...

### ISSUE THREAD

**Issue by ttsiodras** [TypeStrong/grunt-ts#14]
As per your SO response, I tried using grunt-ts in my project - but see this:

```
In folder /home/ttsiod/work/work3/codeGen/Customers-war/src/TypeScript
$ cat Gruntfile.js 
module.exports = function (grunt) {
    // load the task 
    grunt.loadNpmTasks("grunt-ts");
    // Configure grunt here  
    grunt.initConfig({
        ts: {            
            dev: {                                 // a particular target   
                src: ["Customers/**/*.ts", "RTL/**/*.ts"],
                reference: "Customers/reference.ts",
                out: 'Customers/script.js',
                watch: 'Customers', 
                options: {
                    target: 'es5',
                    sourcemap: true
                }
            }
        }
    });
    grunt.registerTask("default", ["ts:dev"]);
};

In folder /home/ttsiod/work/work3/codeGen/Customers-war/src/TypeScript
$ grunt
Running "ts:dev" (ts) task
Compiling.

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/ttsiod/work/work3/codeGen/Customers-war/src/TypeScript/undefined/tsc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
>> Compilation failed
Watching all TypeScript / Html files under : /home/ttsiod/work/work3/codeGen/Customers-war/src/TypeScript/Customers
```

Any ideas what could be wrong? I used the same setup as your tutorial video (Animal / Cow / etc) where it worked fine - but with my project I see this error. How to debug it?

**Comment by flyon** [comment]
I didnt have any local reference to typescript yet, just the global one. I did `npm link typescript` and then it worked
