### ISSUE TITLE
Error installing grunt-ts

### ISSUE THREAD

**Issue by pnahtanoj** [TypeStrong/grunt-ts#365]
Attempting to install grunt-ts in my project is giving me the following error.  I'm not convinced it's a grunt-ts problem, but I'm at a loss on how to correct it.  

> fsevents@0.3.8 install /Users/jonathanprice/Websites/bookinghelper/node_modules/grunt-ts/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jonathanprice/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "node" "/Users/jonathanprice/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jonathanprice/Websites/bookinghelper/node_modules/grunt-ts/node_modules/fsevents
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.5.0
npm ERR! argv "node" "/Users/jonathanprice/.npm-packages/bin/npm" "install" "grunt-ts" "--save-dev"
npm ERR! node v0.12.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonathanprice/Websites/bookinghelper/npm-debug.log

**Comment by pnahtanoj** [comment]
I just --force'd it and all is well (as best I can tell)
