### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by pocesar** [TypeStrong/grunt-ts#366]
```
g:\www\neuro>grunt ts
Running "ts:server" (ts) task
Compiling...
Cleared fast compile cache for target: server
### Fast Compile >>typings/generic.d.ts
### Fast Compile >>src/server/app.ts
### Fast Compile >>src/server/models/admin.ts
### Fast Compile >>src/server/models/comissao.ts
### Fast Compile >>src/server/models/cortesia.ts
### Fast Compile >>src/server/models/test.ts
### Fast Compile >>src/server/models/transaction.ts
### Fast Compile >>src/server/models/user.ts
### Fast Compile >>src/server/modules/common.ts
### Fast Compile >>src/server/modules/correios.ts
### Fast Compile >>src/server/modules/formulas.ts
### Fast Compile >>src/server/modules/mandrill.ts
### Fast Compile >>src/server/modules/moip.ts
### Fast Compile >>src/server/modules/mongoose.ts
### Fast Compile >>src/server/modules/pagination.ts
### Fast Compile >>src/server/modules/templates.ts
### Fast Compile >>src/server/pages/admin/index.ts
### Fast Compile >>src/server/pages/buy/index.ts
### Fast Compile >>src/server/pages/email/index.ts
### Fast Compile >>src/server/pages/questionario/index.ts
### Fast Compile >>src/server/pages/site/index.ts
### Fast Compile >>src/server/pages/user/index.ts
Using tsc v2.0.0-dev.20160707
g:\www\neuro\node_modules\typescript\lib\tsc.js:36916
                throw e;
                ^

TypeError: Cannot read property 'id' of undefined
    at getNodeId (g:\www\neuro\node_modules\typescript\lib\tsc.js:13014:18)
    at getNodeLinks (g:\www\neuro\node_modules\typescript\lib\tsc.js:13402:26)
    at checkExpressionCached (g:\www\neuro\node_modules\typescript\lib\tsc.js:22848:25)
    at g:\www\neuro\node_modules\typescript\lib\tsc.js:15426:94
    at Object.map (g:\www\neuro\node_modules\typescript\lib\tsc.js:199:29)
    at getTypeOfVariableOrParameterOrProperty (g:\www\neuro\node_modules\typescript\lib\tsc.js:15426:44)
    at getTypeOfSymbol (g:\www\neuro\node_modules\typescript\lib\tsc.js:15561:24)
    at checkPropertyAccessExpressionOrQualifiedName (g:\www\neuro\node_modules\typescript\lib\tsc.js:21042:28)
    at checkPropertyAccessExpression (g:\www\neuro\node_modules\typescript\lib\tsc.js:21007:20)
    at checkExpressionWorker (g:\www\neuro\node_modules\typescript\lib\tsc.js:22937:28)

>> Error: tsc return code: 1
Warning: Task "ts:server" failed. Use --force to continue.

Aborted due to warnings.
```

can't use typescript@next anymore, I was able to at least "half" compile the project

**Comment by nycdotnet** [comment]
I just pushed `grunt-ts@6.0.0-beta.1` which should work with typescript@next (no native support for the new features yet).  Would you please try with that version?

**Comment by nycdotnet** [comment]
Hi @pocesar - the error you've reported came from the tsc `20160707` nightly.  It was not raised in grunt-ts, so I am not sure that this is actionable for us.  Please reopen this if you're still having the trouble with a more recent compiler and post the results with `--verbose` active for Grunt.  Thank you for the report.

**Comment by pocesar** [comment]
no problem, I'm not using grunt-ts anymore, using my own grunt plugin, thanks

**Comment by nycdotnet** [comment]
ok thanks.  Good luck.
