### ISSUE TITLE
Error running grunt-ts from VS2015 after update to typescript 3.1.1

### ISSUE THREAD

**Issue by Songissimo** [TypeStrong/grunt-ts#428]
Hi All,
    after upgrading typescript to version 3.1.1 if run grunt-ts from VS2015 task runner I get the following error:

...\lib\tsc.js:73583
    var ignoredProperties = new Set(["arguments", "caller", "constructor", "ev
                                                    ^
ReferenceError: Set is not defined
    at ts (...\tsc.js:73583:33)
    at Object.<anonymous> (...\typescript\lib\tsc.js:73631:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>( ...\typescript\bin\tsc:2:1)
    at Module._compile (module.js:456:26)
 Error: Node was unable to run tsc.  Possibly it could not be found?
Warning: Task "ts:default" failed. Use --force to continue.
Aborted due to warnings.
Process terminated with code 3.

What's wrong with it?

It's weird that I don't get any issu running it from command line.

Thanks everybody.

**Comment by nycdotnet** [comment]
Seems like VS is using an old version of Node (Set is an ES6 thing).  Try accepted answer here: https://stackoverflow.com/questions/43849585/update-node-version-in-visual-studio-2017
